#!/usr/bin/env python

import sys
import numpy as np
import obspy
import matplotlib.pyplot as plt
from scipy.fftpack import fft, fftfreq
from scipy import signal
from obspy.core import read
from glob import glob

files = glob('*.sac')
stats = read(files[0])[0].stats

dt = stats.delta
nt = stats.npts

t = np.zeros(nt, dtype='float32')
for i in range(nt):
	t[i] = i * dt

for file in files:
	if len(sys.argv > 1) and sys.argv[1] not in file:
		continue

	trace = read(file)[0]
	plt.plot(t, trace.data)
	plt.xlabel('Time / hour')
	plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))

plt.show()
